name: Build/release

on: [push]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build/release Electron app
        uses: crazy-max/ghaction-electron-builder@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # The release option determines whether a new GitHub release should be created
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          # Optional: specify the command to run for building, if not default
          # build_command: "npm run dist" 
          # Optional: specify the root of your app, if not the repository root
          # app_root: "." 
